# Generated by Django 3.2.4 on 2021-07-12 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('name', models.CharField(default='anonymous', max_length=200)),
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200, null=True)),
                ('topic', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('privacy', models.CharField(default='Private', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('name', models.CharField(default='anonymous', max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('repid', models.AutoField(primary_key=True, serialize=False)),
                ('reply', models.CharField(max_length=1000)),
                ('forum', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forum')),
            ],
        ),
    ]
