# Generated by Django 3.1.13 on 2021-07-13 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='memeber_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply_thread',
            fields=[
                ('name', models.CharField(default='anonymous', max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('repid', models.AutoField(primary_key=True, serialize=False)),
                ('reply', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('name', models.CharField(default='anonymous', max_length=200)),
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200, null=True)),
                ('topic', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('privacy', models.CharField(default='Private', max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='tid',
            new_name='fid',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.AddField(
            model_name='thread',
            name='forum',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forum'),
        ),
        migrations.AddField(
            model_name='reply_thread',
            name='thread',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum.thread'),
        ),
        migrations.AddField(
            model_name='memeber_info',
            name='forum',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forum'),
        ),
    ]
