# Generated by Django 3.1.13 on 2021-07-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210713_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='memeber_info',
            name='name',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
