# Generated by Django 3.1.13 on 2021-07-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_memeber_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
